services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: usage_app
      POSTGRES_PASSWORD: usage_app
      POSTGRES_DB: usage_db
    volumes:
      - /kubeflow_cephfs/usage_portal_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U usage_app -d usage_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
